Feature/my page
shinonome-inc/qiita_client_yukik pull request #10
Opened 2023-04-15 17:08 UTC by yukik8

マイページの実装を行いました。認証を行う際はGoogleドライブのeducation_mobile/YukiKフォルダ内にある.envファイルをqiita_client_yukik直下に入れてください。
未ログイン時
<img src="https://user-images.githubusercontent.com/111037635/232238480-ced2906c-423e-4081-8e91-88e556f7ccb6.png" width="300">
ログイン時
<img src="https://user-images.githubusercontent.com/111037635/232240331-a0be768f-d6b3-4392-8548-a3ee6b105acf.png" width="300">

2023-04-16 01:00 UTC, ShuheiYoshidaJP commented
https://dart.dev/guides/language/effective-dart/style#do-name-packages-and-file-system-entities-using-lowercase-with-underscores
ソースファイルの名前には、小文字とアンダースコアを使った方がいいですね。

├── lib
│   ├── main.dart
│   ├── models
│   │   ├── accessToken.dart
│   │   ├── article.dart
│   │   ├── fetchArticle.dart ←
│   │   ├── fetchTag.dart ←
│   │   ├── fetchTagDetail.dart ←
│   │   ├── fetchUsersArticle.dart ←
│   │   ├── tag.dart
│   │   ├── user.dart
│   │   └── usersArticle.dart ←
│   ├── pages
│   │   ├── feed_detail.dart
│   │   ├── feed_page.dart
│   │   ├── login_page.dart
│   │   ├── mypage.dart
│   │   ├── mypage_notlogin.dart
│   │   ├── tag_detail.dart
│   │   ├── tag_page.dart
│   │   └── top_page.dart
│   └── root.dart
├── pubspec.lock
├── pubspec.yaml
└── test
    └── widget_test.dart

2023-04-16 01:12 UTC, ShuheiYoshidaJP commented
```
│   ├── models
│   │   ├── accessToken.dart <-
│   │   ├── article.dart
│   │   ├── fetchArticle.dart <-
│   │   ├── fetchTag.dart <-
│   │   ├── fetchTagDetail.dart <-
│   │   ├── fetchUsersArticle.dart <-
│   │   ├── tag.dart
│   │   ├── user.dart
│   │   └── usersArticle.dart
```
modelsディレクトリは、通常、データモデルやオブジェクトを定義するために使用されるべきで、HTTP通信のような処理は含めないほうが良いと思います。
代わりに、新しいディレクトリ（例えば services または api といった名前）を作成し、そこにHTTP通信やAPI呼び出しに関する処理を移動することをお勧めします。
```
lib
├── main.dart
├── models
├── pages
├── services
└── root.dart
```
こんな感じのですね。

2023-04-16 01:18 UTC, ShuheiYoshidaJP commented on lib/models/fetchUsersArticle.dart
> +        'Authorization': 'Bearer f7cbc007e8b546e5169c6aaf4a5f41df1a950668'
Auth認証で取得したアクセストークンを使うべきだと思います。

2023-04-16 01:20 UTC, ShuheiYoshidaJP reviewed
http通信行うクラスを別で切り出し、共通化した方がいいかなと思いました！

2023-04-16 01:20 UTC, ShuheiYoshidaJP commented on lib/models/accessToken.dart
> +    }
ここ

2023-04-16 01:20 UTC, ShuheiYoshidaJP commented on lib/models/accessToken.dart
> +    }
ここ

2023-04-16 01:20 UTC, ShuheiYoshidaJP commented on lib/models/fetchUsersArticle.dart
> +    }
ここ

2023-04-17 12:37 UTC, ShuheiYoshidaJP commented
lib/pages/login_page.dart
``` dart
  Future<void> _login(String url) async {
    String? code = Uri.parse(url).queryParameters['code'];
    print("code: $code");
    final String accessToken = await AccessToken().createAccessToken(code!);
    print("accessToken: $accessToken");
    _authenticatedUser =
        await AccessToken().fetchAuthenticatedUser(accessToken);
    print("_authenticatedUser: $_authenticatedUser");
  }
```
こんな感じのデバック文を張ってみたんですけど、
ちゃんと出力されましたよ。
どのような手順を踏んだら、yukiさんと同じ不具合が再現できるかを示してもらえると助かります。

2023-04-22 03:31 UTC, ShuheiYoshidaJP reviewed
baseUrlについてコメントしました。
本来であればbaseUrlとpathで分けるべきかなと思います。

2023-04-22 03:31 UTC, ShuheiYoshidaJP commented on lib/services/access_token.dart
> +  final String baseUrl = 'https://qiita.com/api/v2/authenticated_user';
baseUrlではなく、別の名前がいいのではと思いました。

2023-04-22 03:31 UTC, ShuheiYoshidaJP commented on lib/services/fetch_article.dart
>    final baseUrl = 'https://qiita.com/api/v2/items';
baseUrlではなく、別の名前がいいのではと思いました。

2023-04-22 03:31 UTC, ShuheiYoshidaJP commented on lib/services/fetch_tag_detail.dart
>    final baseUrl = 'https://qiita.com/api/v2/items';
baseUrlではなく、別の名前がいいのではと思いました。

2023-04-22 03:33 UTC, ShuheiYoshidaJP reviewed
TopPageでは何を担当するのか？LoginPageでは何を担当するのかを意識した方がいいのかなと思います。

2023-04-22 03:33 UTC, ShuheiYoshidaJP commented on lib/pages/top_page.dart
> +  final String clientSecret = dotenv.get('CLIENT_SECRET');
LoginPageで管理すればいいのではと思いました。

2023-04-22 03:33 UTC, ShuheiYoshidaJP commented on lib/pages/top_page.dart
> +                                      'https://qiita.com/api/v2/oauth/authorize?client_id=$clientId&scope=read_qiita&state=bb17785d811bb1913ef54b0a7657de780defaa2d'),
同上

2023-04-22 03:38 UTC, ShuheiYoshidaJP commented on lib/pages/login_page.dart
> +              );
Don't use 'BuildContext's across async gaps.
Try rewriting the code to not reference the 'BuildContext'.

このような警告が出てますね。

2023-04-22 03:39 UTC, ShuheiYoshidaJP commented on lib/pages/tag_detail.dart
> +}
This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: TagDetail.tagName

コンストラクタの定義の仕方を変えればこの警告は消えると思います。

2023-04-22 03:43 UTC, ShuheiYoshidaJP commented on lib/pages/my_page.dart
> +  final List<UsersArticle> fetchedUsersArticles = [];
ChatGPTにStateクラス内でfinalを使っていいのかについて聞いてみました。
```
final を State クラス内で使用することは、一般的には問題ありません。ただし、final は一度初期化されると変更できないため、値が変更されることが想定されるプロパティの場合は適切でないことがあります。State クラス内で、値が変更されることが想定されるプロパティは、final ではなく普通の変数（var や late）を使用してください。
```
このような回答をもらいました。
僕としてはfinalではなくvarを用いた方がいいのではと思いました。

2023-04-22 03:45 UTC, ShuheiYoshidaJP commented
コンフリクトの修正お願いします。

2023-04-22 11:04 UTC, KobayashiYoh requested changes
コメントしました。

2023-04-22 11:04 UTC, KobayashiYoh commented on lib/pages/my_page.dart
> +                            )
ここの部分はUIコンポーネントとして共通化できそうですね

2023-04-22 11:04 UTC, KobayashiYoh commented on lib/pages/my_page.dart
> +                                  ),
記事件数が多い場合、レイアウト崩れが発生しちゃっていますね。
<img src="https://user-images.githubusercontent.com/82624334/233780253-3d101f56-6560-4ad7-8b74-0ec4e83dbec3.png" width="300">

2023-04-22 12:21 UTC, KobayashiYoh requested changes
追加で1点コメントしました。

2023-04-22 12:21 UTC, KobayashiYoh commented on lib/pages/my_page.dart
> +      itemCount: isLoading ? items.length + 1 : items.length,
記事の件数が少ない場合、記事が中央に寄ってしまっていますね。
<img src="https://user-images.githubusercontent.com/82624334/233784480-c4637415-c1c0-42be-b5ec-9c89136dc5fd.png" width="300">

2023-04-22 12:22 UTC, merged

2023-04-22 12:23 UTC, KobayashiYoh approved these changes