Feature/test modify
shinonome-inc/qiita_client_yukik pull request #13
Opened 2023-05-26 11:32 UTC by yukik8

テスト実行を行い、新たに以下を実装しました。
・Feed page, Tag pageにおけるpull to refresh
・キーボード外をタップまたはlistViewをスクロールでキーボードを隠す
・キーボードの入力内容を消去するボタン
・検索結果を２ページ目ではなく１ページ目から表示
・pubspec.yaml内の.envファイルの名前を修正

2023-05-26 13:45 UTC, KobayashiYoh requested changes
エラーが出ていてビルドできないですね…。

2023-05-26 13:45 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
>            mainAxisAlignment: MainAxisAlignment.center,
Columnにconstをつけているのが原因でエラーが発生しているため、ビルドができないです。

2023-05-26 13:45 UTC, KobayashiYoh commented on lib/pages/tag_page.dart
> +          children: [
こちらもColumnにconstがついているため、エラーが発生しちゃっていますね。

2023-05-27 08:25 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
> +        itemCount: _isLoading ? items.length + 1 : items.length,
`ScrollViewKeyboardDismissBehavior.onDrag`
これ知らなかったです。とても勉強になりました！

2023-05-27 08:25 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
> +        ),
👍

2023-05-27 08:25 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
> +                child: Column(
これも初めて知りました！

2023-05-27 08:39 UTC, KobayashiYoh commented
## 修正した方が良い点
* TagDetailPageでpull to refreshが作動していない
* MyPageでpull to refreshが動作していない

2023-05-27 12:33 UTC, KobayashiYoh approved these changes

2023-05-27 16:20 UTC, kota78 commented
レビュー対象箇所はOKだと思います！
一点だけ、ログイン後のFeedPageでAppBarの左部分をタップするとログインページに戻ってしまうようです。`Navigator.push`で遷移していると思いますが、別の遷移方法を試してみてほしいです。
[参考](https://itome.team/blog/2019/12/flutter-advent-calendar-day10/)
https://github.com/shinonome-inc/qiita_client_yukik/assets/82959924/ad21d03c-c504-4314-83e1-294cc16a3841
他は完璧です！！

2023-05-28 16:13 UTC, kota78 commented on lib/pages/error_page.dart
> +    return WillPopScope(
RootのScaffoldをWrapすれば一個ですみそう！

https://github.com/shinonome-inc/qiita_client_yukik/assets/82959924/f3056273-e417-4749-a5ca-f564a88401cf

WillPopScopeだけだとボタンが残り続けるようです。`AppBarComponent`に何か1行加えれば完璧です！

2023-05-29 05:28 UTC, yukik8 commented on lib/pages/error_page.dart
> +    return WillPopScope(
確かに、、！気付けなくて無駄な手間かけちゃってました！！勉強になりました🙏

2023-05-29 07:47 UTC, kota78 commented
LGTMです！！！

2023-05-30 02:49 UTC, mcz9mm commented
プロフィールのnameを設定してない人は空文字が返ってきてしまっているので見え方を直してほしいです。
<img width="300" alt="スクリーンショット 2023-05-30 11 47 56" src="https://github.com/shinonome-inc/qiita_client_yukik/assets/11751495/80a410d3-bd23-4c5e-8054-27cbe45e40ca">

nameが空文字の時はuserIdを表示する

該当箇所
```
                              Text(
                                authenticatedUser.name,
                                style: const TextStyle(
                                  fontSize: 14,
                                  fontWeight: FontWeight.w500,
                                ),
                              ),
```

2023-05-30 04:35 UTC, mcz9mm requested changes

2023-05-30 04:35 UTC, mcz9mm commented on lib/pages/my_page.dart
> +                              ? const SizedBox(height: 0)
細かいけど`const SizedBox.shrink()`で！
> FlutterのSizedBox.shrink()は、サイズを0に設定するウィジェットです。主に、他のウィジェットを配置する際に、間隔を空けたくない場合に使用されます。例えば、RowやColumnの中でウィジェットを配置するときに、間隔を空けずにウィジェットを並べたい場合に使用できます。

2023-05-30 05:00 UTC, mcz9mm approved these changes
LGTM

2023-06-03 07:03 UTC, merged