Feature/bottom navigation bar
shinonome-inc/qiita_client_yukik pull request #3
Opened 2022-12-18 01:57 UTC by yukik8

![image](https://user-images.githubusercontent.com/111037635/208276022-0600d18b-ee9d-4bca-885b-fa7f37dcb733.png)
Bottom Navigation Barを作りました。

2022-12-18 02:34 UTC, Yoshida-koshi reviewed
コメントしました〜

2022-12-18 02:34 UTC, Yoshida-koshi commented on lib/main.dart
> +      home: const Root(),
検証用で設定した場合は元に戻すようにしてください！

2022-12-18 02:34 UTC, Yoshida-koshi commented on lib/root.dart
> +          type: BottomNavigationBarType.fixed,
BottomNavigationBarで遷移するときに固定表示できていて素晴らしいです！

2022-12-18 02:46 UTC, Yoshida-koshi commented on lib/main.dart
> +      home: const Root(),
OKです！

2022-12-18 02:47 UTC, Yoshida-koshi commented
僕はLGTMなので、2次レビューを依頼してください！

2022-12-18 03:18 UTC, KobayashiYoh requested changes
2点コメントしました。

2022-12-18 03:18 UTC, KobayashiYoh commented on lib/models/article.dart
> +}
今回の実装と関係ないファイルをGitの差分に入れるのはなるべく避けましょう。
`lib/models/user.dart`と`lib/pages/feed_page.dart`、`pubspec.lock`、`pubspec.yaml`に関しても同様です。
次からは気をつけましょう。

2022-12-18 03:18 UTC, KobayashiYoh commented on lib/root.dart
> +  const Root({super.key});
Rootクラスの実装自体はよくできていて素晴らしいです👍
ただ、現状の実装だとせっかく実装したBottomNavigationBarが表示されていないです…。
TopPageの「ログインせずに利用する」をタップしたらRootへ画面遷移できるようにしましょう。
詳しくは、figmaの「画面遷移」や「画面要件」をご覧ください。

2022-12-21 14:42 UTC, KobayashiYoh approved these changes
コメントしました。
BottomNavigationBarの基本的な機能は部分はしっかり修正できているため修正は任意です。

2022-12-21 14:42 UTC, KobayashiYoh commented on lib/root.dart
> +        child: BottomNavigationBar(
BottomNavigationBarをSizedBoxで囲むと端末によってレイアウト崩れの原因になるみたいです。
iPhone 14だと以下のように表示されました。
<img src="https://user-images.githubusercontent.com/82624334/208930945-d270ca65-2a0e-42c5-b3ba-adbd9264420b.png" width="300">

2022-12-21 14:42 UTC, KobayashiYoh commented on lib/root.dart
> +            ),
`Icons.label_outline`のようにアイコン名の後ろに`_outline`をつけてあげるとfigmaのような塗りつぶしではないアイコンを表示してくれます。

2022-12-21 14:53 UTC, merged