タグページの実装
shinonome-inc/qiita_client_yukik pull request #8
Opened 2023-03-24 17:03 UTC by yukik8

タグページの実装を行いました。
![image](https://user-images.githubusercontent.com/111037635/227592516-e9341096-bbd0-4023-9809-a321c4091810.png)

2023-03-24 17:47 UTC, Yoshida-koshi reviewed
コメントしました〜

2023-03-24 17:47 UTC, Yoshida-koshi commented on lib/models/fetchTag.dart
> +    print('通信中');
print文は検証用に使うので、PR出す時点では消しておいた方がいいです！
何個か他にもあるので、お願いします！

2023-03-24 17:47 UTC, Yoshida-koshi commented on lib/pages/tag_page.dart
> +          final newArticles = await ApiTag().fetchTag(page: _pageNumbers);
今回はTagなので、newArticlesではなくてnewTagsの方がいいと思います！

2023-03-24 17:47 UTC, Yoshida-koshi commented on lib/pages/tag_page.dart
> +                  (MediaQuery.of(context).size.width / (138 + 16)).toInt()),
138 + 16とはどこを参照したものですか？

2023-03-24 17:47 UTC, Yoshida-koshi commented on lib/pages/tag_page.dart
> +                      '投稿件数：${tags[index].itemsCount.toString()}',
${}の中身はint型で指定できるので、toStringは要らないです！

2023-03-24 17:47 UTC, Yoshida-koshi commented on lib/pages/tag_page.dart
> +              ),
なんで白いContainerを入れたんですか？

2023-03-24 17:47 UTC, Yoshida-koshi commented on lib/pages/tag_page.dart
> +                        ]),
TagPageは検索はいらないと思います！

2023-03-25 07:25 UTC, yukik8 commented on lib/pages/tag_page.dart
> +                  (MediaQuery.of(context).size.width / (138 + 16)).toInt()),
figmaで使われていた端末では１つのタグのブロックの横幅が138、左右のスペースが16だったのでその数で割れば良い感じに実装されるかと考えました。

2023-03-27 03:13 UTC, Yoshida-koshi commented
https://github.com/shinonome-inc/qiita_client_yukik/pull/8#discussion_r1147881375
↑の対応お願いします！

2023-03-27 09:48 UTC, Yoshida-koshi commented
検証用のコードの削除はOKです！基本的にprint文は最終的には消すものなので、これからもその方針でいって欲しいです！

2023-03-27 09:52 UTC, Yoshida-koshi reviewed
コメントしました〜

2023-03-27 09:52 UTC, Yoshida-koshi commented on lib/pages/tag_page.dart
> +      final newArticles = await ApiTag().fetchTag(page: _pageNumbers);
まだnewTagsになってないですね！

2023-03-27 09:52 UTC, Yoshida-koshi commented on lib/pages/tag_page.dart
> +                  (MediaQuery.of(context).size.width / (138 + 16)).toInt()),
<img width="986" alt="スクリーンショット 2023-03-27 12 19 56" src="https://user-images.githubusercontent.com/85224998/227832693-95af9e1a-5996-409c-8cf8-67855d41dde2.png">

Figmaだと横幅が162だと思います！

2023-03-27 09:52 UTC, Yoshida-koshi commented on lib/pages/tag_page.dart
> +                      '投稿件数：${tags[index].itemsCount.toString()}',
OKです！

2023-03-27 09:52 UTC, Yoshida-koshi commented on lib/pages/tag_page.dart
> +              ),
OKです！

2023-03-27 09:52 UTC, Yoshida-koshi commented on lib/pages/tag_page.dart
> +                        ]),
OKです！

2023-03-27 09:52 UTC, Yoshida-koshi commented on lib/pages/tag_page.dart
> +      final newArticles = await ApiTag().fetchTag(page: _pageNumbers);
今回はTagなのでnewArticlesではなくnewTagsの方がいいと思います！

2023-03-27 10:16 UTC, Yoshida-koshi reviewed
1点だけコメントしました〜

2023-03-27 10:16 UTC, Yoshida-koshi commented on lib/pages/tag_page.dart
> +                        builder: (context) => TagDetail(tagName: tagName)));
TagDetailの部分エラー出てませんか？

2023-03-27 10:28 UTC, Yoshida-koshi commented on lib/pages/tag_page.dart
> +                        builder: (context) => TagDetail(tagName: tagName)));
TagDetailは別で作っているのでOK！

2023-03-27 10:28 UTC, Yoshida-koshi commented
LGTMです！2次レビューをお願いしてください！

2023-03-30 14:09 UTC, KobayashiYoh commented
TagDetailPageが存在しないため、TagPageでエラーが出ちゃっていますね。
<img width="1076" alt="スクリーンショット 2023-03-30 23 07 52" src="https://user-images.githubusercontent.com/82624334/228862848-aac0059c-0d9c-4d7b-8dd8-a53935d0bdb6.png">

2023-03-30 15:14 UTC, KobayashiYoh requested changes
4点コメントしました。

2023-03-30 15:14 UTC, KobayashiYoh commented on lib/models/tag.dart
> +        followersCount: json['followers_count']);
ある一定の所までスクロールすると、スクロールできなくなってしまいますね…。

https://user-images.githubusercontent.com/82624334/228874921-3be8517c-3986-4d38-9968-ac52bf40570a.mov

2023-03-30 15:14 UTC, KobayashiYoh commented on lib/models/tag.dart
> +        followersCount: json['followers_count']);
この時、コンソールには以下のようなエラーが表示されています。
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
#0      new Tag.fromJson (package:qiita_client_yukik/models/tag.dart:15:22)
#1      ApiTag.fetchTag.<anonymous closure> (package:qiita_client_yukik/models/fetchTag.dart:22:20)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#6      new List.of (dart:core-patch/array_patch.dart:51:28)
#7      ListIterable.toList (dart:_internal/iterable.dart:213:44)

```

2023-03-30 15:14 UTC, KobayashiYoh commented on lib/pages/tag_page.dart
> +      child: Padding(
（現時点の）168行目にExpandedが存在しているため、ここのExpandedは削除しておくといいかもしれませんね。
ここのExpandedが原因でエラーが出ています。

2023-03-30 15:14 UTC, KobayashiYoh commented on lib/pages/tag_page.dart
> +                    ),
レイアウト崩れが表示されているため、画像のエラー処理を入れた方がいいかもしれないですね。
<img src="https://user-images.githubusercontent.com/82624334/228882699-7a26c6fa-7387-410d-ac18-e619311c0e37.png" width="300">

2023-03-30 15:21 UTC, KobayashiYoh commented on lib/models/tag.dart
> +        followersCount: json['followers_count']);
nullの扱いについてはこの記事が参考になるかもしれないです。
https://doitu.info/blog/5ca2142a8dbc7a001af33cf5

2023-03-30 15:26 UTC, KobayashiYoh commented on lib/pages/tag_page.dart
> +                    ),
この記事が参考になりそうです。
https://nobushiueshi.com/flutterimage-network%E3%81%A7%E7%94%BB%E5%83%8F%E3%81%AE%E5%8F%96%E5%BE%97%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%8B%E3%81%A3%E3%81%9F%E6%99%82%E3%81%AE%E3%82%A8%E3%83%A9%E3%83%BC%E4%BE%8B/

2023-03-30 15:45 UTC, KobayashiYoh commented
しっかり修正できています！
LGTMです！

2023-03-30 15:46 UTC, KobayashiYoh approved these changes

2023-03-30 15:46 UTC, merged